---
- name: Install server.hcl
  template:
    src: server.hcl.j2
    dest: /tmp/server.hcl

- name: Run nomad server
  shell: daemon -U -o /tmp/nomad-server.log -- nomad agent -config /tmp/server.hcl && sleep 3

- name: Connect to the other servers
  shell: nomad server-join {{ hostvars[item]['ansible_eth0']['ipv4']['address'] }}
  with_items:
    - node01
    - node02
    - node03

