---
- name: Install server.hcl
  template:
    src: server.hcl.j2
    dest: /tmp/server.hcl

- name: Run nomad server
  shell: daemon -U -o /tmp/nomad-server.log -- nomad agent -config /tmp/server.hcl && sleep 3

- name: Connect to the other servers
  shell: nomad server-join 192.168.0.101 192.168.0.102 192.168.0.103
