---
- name: Install nomad
  hosts: nomad-nodes
  sudo: yes

  roles:
    - common

- name: Launch and coordinate nomad servers
  hosts: nomad-servers
  sudo: yes
  roles:
    - servers

- name: Launch nomad clients
  hosts: nomad-clients
  sudo: yes
  roles:
    - clients

- name: Dispatch a job to the cluster
  hosts: node01
  sudo: yes
  roles:
    - jobs
