---
- name: Add docker group
  group:
    name: docker
    state: present

- name: Add nomad user to docker group
  user:
    name: nomad
    groups: docker
    append: true

- name: Install client.hcl
  template:
    src: client.hcl.j2
    dest: /tmp/client.hcl

- name: Run nomad client
  shell: daemon -U -o /tmp/nomad-client.log -- nomad agent -config /tmp/client.hcl && sleep 20
