---
- name: Copy job definition
  template:
    src: example.nomad.j2
    dest: /tmp/example.nomad

- name: Dispatch job
  command: nomad run /tmp/example.nomad

- name: Wait a while and then inspect job status
  shell: sleep 15 && nomad status example
  register: status

- debug: var=status

- name: Stop job
  command: nomad stop example

