---
- name: Copy job definition
  template:
    src: example.nomad.j2
    dest: /tmp/example.nomad

- name: Dispatch job
  command: nomad run /tmp/example.nomad

- name: Inspect job status
  shell: nomad status example
  register: status

- debug: var=status
