---
- name: Install dependencies
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - unzip
    - curl
    - wget
    - gnupg
    - daemon

# TODO: Rather than having every node download and verify nomad, do it
# once on one machine and distribute the binary.

- name: Deploy Hashicorp public key file
  copy:
    src: hashicorp.asc
    dest: /tmp/hashicorp.asc

- name: Import Hashicorp key
  command: gpg --import /tmp/hashicorp.asc

- name: Download SHA256 checksum file and signature file
  get_url:
    url: "https://dl.bintray.com/mitchellh/nomad/nomad_{{ nomad_version }}_{{ item }}"
    dest: "/tmp/nomad_{{ nomad_version }}_{{ item }}"
  with_items:
    - "SHA256SUMS"
    - "SHA256SUMS.sig"

- name: Verify signature for SHA256 checksum file
  command: "gpg --verify /tmp/nomad_{{ nomad_version }}_SHA256SUMS.sig /tmp/nomad_{{ nomad_version }}_SHA256SUMS"

- name: Download nomad
  get_url:
    url: "https://dl.bintray.com/mitchellh/nomad/nomad_{{ nomad_version }}_linux_amd64.zip"
    dest: "/tmp/nomad_{{ nomad_version }}_linux_amd64.zip"

- name: Verify nomad SHA256 checksum
  shell: "grep $(sha256sum /tmp/nomad_{{ nomad_version }}_linux_amd64.zip | cut -d' ' -f1) /tmp/nomad_{{ nomad_version }}_SHA256SUMS"

- name: Install nomad
  unarchive:
    copy: false
    src: "/tmp/nomad_{{ nomad_version }}_linux_amd64.zip"
    dest: /usr/local/bin

- file:
    path: /usr/local/bin/nomad
    mode: 0755
